version: 2.1
image: &image
   docker:
    - image: circleci/node:13.8.0
jobs:
  build_step:
    build: 
    <<: *image
    steps:
      - checkout
      - run: npm i
      - save_cache:
          paths:
            - /src/node_modules
          key: "npm-packages"
      - run: npm run lint
  test:
    build: 
    <<: *image
    steps:
      - checkout
      - restore_cache:
          key: "npm-packages"
      - run: npm i
      - run: npm run test
  analyze:
    build: 
    <<: *image
    steps:
      - checkout
      
      - restore_cache:
          key: "npm-packages"
      - run: npm i
      - run: npm audit

workflows:
  circleci-workflow:
    jobs:
      - build_test
      - test:
          requires:
            - build_test
      - analyze:
          requires:
            - test




